name 'Configure_SQL_Disk_F'
maintainer 'Ryan Irujo'
maintainer_email 'ryan.irujo@gmail.com'
license 'Apache 2.0'
description 'Creates and Formats a New Partitation for a SQL Install on Drive Letter F.'
long_description 'Creates and Formats a New Partitation for a SQL Install on Drive Letter F.'
version '0.1.0'
