name 'Install_SQL_Server_2014_SP1'
maintainer 'karthik'
maintainer_email 'karthik.ramamoorthy@outlook.com'
license 'all_rights'
description 'Installs/Configures Install_SQL_Server_2014_SP1'
long_description 'Installs/Configures Install_SQL_Server_2014_SP1'
version '0.1.0'
depends 'windows_ad','>= 0.4.5'